## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
#Tue Aug 18 17:12:22 CET 2026
android.useAndroidX=true
org.gradle.configureondemand=false
org.gradle.daemon=true
org.gradle.daemon.idletimeout=10800000
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx1024M" -Dfile.encoding\=UTF-8 -XX\:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.workers.max=2
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8
systemProp.user.country=US
systemProp.user.language=en
org.gradle.configuration-cache=true
android.builtInKotlin=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE
android.dependencyResolution.checks=false
android.dependencyResolution.timing=false